entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure: # this name will be used in dynamic config files, in the entryPoints sections of the routers
    address: ":443"

certificatesResolvers:
  letsencrypt: # this name will be used in dynamic config files, in the tls.certResolver section of the routers
    acme:
      tlsChallenge: {}
      email: your-email@example.com # Change this, of course
      storage: /letsencrypt/acme.json # Mapped in docker-compose.yml

providers:
  file:
    directory: /etc/traefik/dynamic-config
    watch: true
# Uncomment the following section to enable logs as needed
#log:
#  level: INFO
